version: "3.9"
services:
  oracle-xe:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: oracle
    volumes:
      - ../../oracle-data:/opt/oracle/oradata
    restart: unless-stopped
