-- 07_triggers.sql (auditoria ALERT)
CREATE OR REPLACE TRIGGER TRG_ALERT_AIUD_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON ALERT
FOR EACH ROW
DECLARE
  V_ACTION VARCHAR2(50);
  V_MSG    VARCHAR2(400);
BEGIN
  IF INSERTING THEN
    V_ACTION := 'INSERT';
    V_MSG := NVL(:NEW.MESSAGE, 'sem mensagem');
    INSERT INTO AUDIT_LOG (ENTITY, ENTITY_ID, ACTION, DETAILS)
    VALUES ('ALERT', :NEW.ALERT_ID, V_ACTION, 'Novo ALERT nível '||:NEW.LEVEL||' - '||V_MSG);
  ELSIF UPDATING THEN
    V_ACTION := 'UPDATE';
    V_MSG := NVL(:NEW.MESSAGE, 'sem mensagem');
    INSERT INTO AUDIT_LOG (ENTITY, ENTITY_ID, ACTION, DETAILS)
    VALUES ('ALERT', :NEW.ALERT_ID, V_ACTION, 'Atualizado ALERT -> nível '||:NEW.LEVEL||' - '||V_MSG);
  ELSIF DELETING THEN
    V_ACTION := 'DELETE';
    INSERT INTO AUDIT_LOG (ENTITY, ENTITY_ID, ACTION, DETAILS)
    VALUES ('ALERT', :OLD.ALERT_ID, V_ACTION, 'ALERT removido');
  END IF;
END;
/
SHOW ERRORS;
