
-- 08_user_profile.sql  (Smart HAS – Perfil do usuário para dieta)
-- Cria tabela simples para armazenar perfil e metas de dieta
CREATE TABLE USER_PROFILE (
  USER_ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  NAME            VARCHAR2(120) NOT NULL,
  AGE             NUMBER,
  WEIGHT_KG       NUMBER(10,2),
  TARGET_CALORIES NUMBER,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Índices auxiliares
CREATE INDEX IDX_USER_PROFILE_NAME ON USER_PROFILE(NAME);
