# application-oracle.yml - exemplo de datasource Oracle
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: smarthas
    password: smarthas
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    show-sql: true